-- ============================================================================= 
-- Author:  <Fernando Villaamil>
-- Created Date: <01/10/2020>
-- Description: <List Active Claims with Inactive Locations>
-- File Name: WCACILOC Active Claims With Inactive Locations.rdl
-- Updated By: <Bhanu P. Bhandari>
-- Updated Date: <02/03/2020>
-- =============================================================================